# Generated by Django 4.1.6 on 2023-10-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
    ]
